version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: pokemon_game_db
    restart: always
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: pokemon_game
      MYSQL_USER: consumer
      MYSQL_PASSWORD: consumer
    ports:
      - "3306:3306"
    volumes:
      - ./pokemon-backend/database/data:/var/lib/mysql
      - ./pokemon-backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pokemon_game_phpmyadmin
    links:
      - db
    depends_on:
      - db
    # env_file:
    #   - .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_USER: consumer
      MYSQL_PASSWORD: consumer
    # PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80

volumes:
  data:
